parameters:
  - name: environment
    type: string
  - name: appName
    default: string
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
  - name: buildConfiguration
    type: string
    default: 'Release'

jobs:
  - deployment: Deploy
    pool:
      vmImage: ${{ parameters.vmImage }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              displayName: 'Deploy to azure app service'
              inputs:
                azureSubscription: 'Resource Manager Exercise Multistage Pipeline'
                appName: ${{ parameters.appName }}
                package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'